# Generated by Django 2.1.4 on 2018-12-22 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('printers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=5, verbose_name='性别')),
                ('units', models.CharField(blank=True, choices=[('ylh', '第一联合运行部'), ('elh', '第二联合运行部')], max_length=5, null=True, verbose_name='单位')),
                ('moblie', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('image', models.ImageField(default='image/default.png', upload_to='image/%y/%m', verbose_name='用户头像')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_printer', to='printers.Prints')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
