# Generated by Django 2.1.4 on 2018-12-23 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181223_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='生日'),
        ),
    ]
