# Generated by Django 2.1.4 on 2018-12-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181223_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='moblie',
            field=models.CharField(default='', max_length=11, verbose_name='手机'),
        ),
    ]
