# Generated by Django 2.1.4 on 2019-01-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181223_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='units',
            field=models.CharField(blank=True, choices=[('ylh', '第一联合运行部'), ('elh', '第二联合运行部'), ('slh', '第三联合运行部'), ('silh', '第四联合运行部'), ('wlh', '第五联合运行部')], max_length=5, null=True, verbose_name='单位'),
        ),
    ]
