# Generated by Django 2.1.4 on 2018-12-22 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(max_length=200, verbose_name='故障类型')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='提交日期')),
                ('receive_date', models.DateTimeField(blank=True, null=True, verbose_name='接收日期')),
                ('over_date', models.DateTimeField(blank=True, null=True, verbose_name='处理完毕日期')),
                ('back_date', models.DateTimeField(blank=True, null=True, verbose_name='取回日期')),
                ('content', models.TextField(verbose_name='故障描述')),
                ('state', models.CharField(choices=[('1', '提交中'), ('2', '已接收'), ('3', '已修好'), ('4', '已确认取回')], default=1, max_length=1)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='管理员备注')),
                ('repair_man', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='form_employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '表单信息',
                'verbose_name_plural': '表单信息',
            },
        ),
    ]
