# Generated by Django 2.1.4 on 2018-12-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printform',
            name='service_category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='故障类型'),
        ),
    ]
