# Generated by Django 2.1.4 on 2018-12-24 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upforms', '0002_auto_20181224_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printform',
            name='repair_man',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='form_employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
