# Generated by Django 2.1.4 on 2018-12-25 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0002_prints_user'),
        ('upforms', '0003_auto_20181224_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='printform',
            name='prints',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='form_pr', to='printers.Prints'),
        ),
    ]
