# Generated by Django 2.1.4 on 2018-12-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.IntegerField(default=0, verbose_name='打印机编码')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='发放日期')),
                ('type', models.CharField(choices=[('1', '惠普7110'), ('2', '惠普1108'), ('3', '三星2070'), ('4', '惠普5200'), ('5', '爱普生1600k')], default=1, max_length=1, verbose_name='打印机型号')),
                ('service_num', models.IntegerField(default=0, verbose_name='维修次数')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='管理员备注')),
            ],
            options={
                'verbose_name': '打印机信息',
                'verbose_name_plural': '打印机信息',
            },
        ),
    ]
