# Generated by Django 2.1.4 on 2018-12-22 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prints',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_printer', to=settings.AUTH_USER_MODEL),
        ),
    ]
