# Generated by Django 2.1.4 on 2019-01-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0006_auto_20190112_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prints',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='发放日期'),
        ),
    ]
